### PR TITLE
✨ #82 Multi-monitor support

### LINKED ISSUE #82: ✨ Multi-monitor support
### Feature Request Description

It would be nice to use a modifier along with the existing shortcuts to move a window to a new monitor. The existing orientation of the window could be preserved or it could just be sent to a generic default position in size on the new monitor.

### Screenshots

_No response_

### Additional Context

_No response_

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

### LINKED ISSUE #163: 🐛 Some percentages don't work on dual monitors.
### Bug Description

When using a specific keybind that cycles between all 6ths of a display, trying to use the shortcut on a top display does not yield the same result as using a bottom display.

### Steps To Reproduce

1. Import my config.
2. Change the "6ths" keyboard shortcut to your preference.
3. Test out all six states on a "bottom" display and observe that it works.
4. Move your mouse to a "top" display (do not click anything with the mouse).
5. Activate your "6ths" keyboard shortcut.
6. Watch as some areas do not snap.

### Expected Behavior

The windows snap to their appropriate corners on both displays, regardless of preview status.

### Actual Behavior

When preview is enabled, windows become glitchy and stick to the bottom display. When preview is disabled, windows snap to odd positions on the top display.

## Display layout
002740@2x

## Video – Preview On
https://github.com/MrKai77/Loop/assets/60551230/c88a6837-42d0-458a-b92f-d8c382e057b8

## Video – Preview Off/On

Uploading 2024-01-13 00-44-45.mp4…

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (620)

### Additional Context

[Loop Keybinds – Bug Report.json](https://github.com/MrKai77/Loop/files/13925011/Loop.Keybinds.Bug.Report.json)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

### LINKED ISSUE #167: 🐛 100% width is applied before movement on multi-displays.
### Bug Description

When moving some apps across multiple displays using the "top" array of actions, the 100% width seems to be applied before movement. As a result, when arriving on the second monitor, the window does not fill the width, but instead seems to match the width of the second monitor.

### Steps To Reproduce

1. Use the attached configuration.
2. Use the "Top Cycle" keyboard shortcut.
3. Transition window from a small display to a larger one.
4. Watch as the window

### Expected Behavior

The window accurately takes up the full width of the display regardless of where it came from.

### Actual Behavior

The window does not take up the full width of the arrival display regardless of where it came from.

## Setup
002764@2x

## Video
https://github.com/MrKai77/Loop/assets/60551230/2863afdd-2698-4215-9991-cf598c1f0a4d

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (621)

### Additional Context

[100% width is applied before.json](https://github.com/MrKai77/Loop/files/13925319/100.width.is.applied.before.json)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

### LINKED ISSUE #168: 🐛 Loop can tell the difference between fast and slow key presses.
### Bug Description

It seems as though Loop can tell the difference between a quick tap and a longer press of a key. When tapping the keyboard shortcut quickly, the "full" action does not occur. Watch the video and see that when the shortcut is tapped, the window does not fully expand to the full screen size as it should.

When clicking the button for slightly longer, the correct actions occur.

### Steps To Reproduce

1. Please use the attached configuration.
2. Move your mouse to the second display.
3. Use the "Maximize" shortcut (any), but quickly tap the key as fast as you can to activate it on the secondary display.
4. Observe that the window does not fully expand on the second display.

5. Move the window back to the smaller monitor.
6. Move your mouse to the second display.
7. Use the "Maximize" shortcut (any), but hold the key down to activate it on the secondary display.
8. Observe that the window fully expands on the second display.

### Expected Behavior

The window expands on the second display regardless of how fast you press a key.

### Actual Behavior

The window expands on the second display depending on how fast you press a key.

### Screenshots

https://github.com/MrKai77/Loop/assets/60551230/9b603040-5d83-4ed0-ba4c-b6995c8b2ba8

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (621)

### Additional Context

[Config.json](https://github.com/MrKai77/Loop/files/13926047/Config.json)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

### LINKED ISSUE #169: 🐛 Mirrored commands don't appear to be mirrored.
### Bug Description

I have two mirrored actions: one moves windows to the left, and the other moves windows to the right.

When using the action that moves windows to the right across screens, everything seems to work fine. However, when arriving on the second display, the window takes up 50% of the left side.

On the other hand, when using the action that moves windows to the left across screens, the window appears in the wrong size when arriving on the second screen, even though the actions are mirrored 1:1 from the right version.

### Steps To Reproduce

1. Use my configuration.
2. Start on a small display.
3. Try using the `⌘ ⌥ ⌃ ⇧ A` shortcut, which moves windows to the left.
4. Repeat the shortcut until the window moves across screens.
5. Observe that the window arrives in an incorrect size.
6. Repeat steps 2-4 using the `⌘ ⌥ ⌃ ⇧ D` shortcut.
7. Observe that the window arrives in a correct size.

### Expected Behavior

When using the shortcuts `⌘ ⌥ ⌃ ⇧ A` and `⌘ ⌥ ⌃ ⇧ D` to move windows to the left and right across screens, respectively, the expected behavior is that the windows should move seamlessly from one screen to the other, maintaining their size and positioning. 

The windows should ideally take up an equivalent proportion of the screen space on the second display as they are described to be.

### Actual Behavior

When using the action that moves windows to the left across screens, the window appears in the wrong size when arriving on the second screen,

## Video

https://github.com/MrKai77/Loop/assets/60551230/4fc2086f-0962-4afc-8e03-4e2f793a4c67

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.13 (621)

### Additional Context

[keybinds.json](https://github.com/MrKai77/Loop/files/13928602/keybinds.json)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

### PR DESCRIPTION
**Pull request by MrKai77**

### CODE REVIEW

**Comment by JaceThings** [comment]
omg yay its soon done

**Comment by MrKai77** [comment]
Alright, here's a working build: [Loop.zip](https://github.com/MrKai77/Loop/files/13924857/Loop.zip)
Please let me know if you notice any bugs :D

There are screen cycling window actions (as any other), and the preset cycle actions will go the next screen when they have reached the end of their cycle on the current screen.
I tried to make it as simple as possible, so the screen recording @Soft-Bred sent in #82 can easily be replicated like this:
image

**Comment by JaceThings** [comment]
I like this a lot! Only one issue, which I don't know if it was introduced in this update, but the ordering of the default "cycle left" and "cycle right" options is odd to me.



1/2 → 1/3 → 2/3

Seems a bit odd to me. I would think it would go:

2/3 → 1/2 → 1/3, biggest to smallest.

Other than that, it works well, but I might have discovered a different unrelated bug.

**Comment by JaceThings** [comment]
Also, just as a pointer, here's the setup I would use personally. :)




Holy shit! After making this setup, as I was writing this comment, it's SO GOOD!! I LOVE IT!!!!

**Comment by MrKai77** [comment]
Awesome!!

Yeahh so about the 1/2, 1/3 then 2/3, that was added back when cycling was first added (before custom keybinds), and I did this because it made the most sense to me to order them by what the user is most likely to try and use.

But now that custom cycling options are available, I've been thinking of totally removing the preset cycling keybinds, so that everything uses the new cycling mechanism (which is wayyy more customizable). So basically, when the app is first downloaded, it would functionally come with the same keybinds, except that the cycling keybinds would look like this:
image
instead of:
image

where the user can add the display cycling themselves if they need to. This is also because on single-monitor setups, I think it looks weird if the window goes to the left of the same monitor when you're cycling on the right side.

Anyways, this is pretty out-of-scope for this issue but I'll probably fix it once this is merged :)
But otherwise, I'm glad to hear that the multi-monitor actions are working well for you! I'll do a bit more testing myself too, but if I find no other issues, I'll merge this later today!

**Comment by MrKai77** [comment]
@Soft-Bred just making sure that #167 and #168 have also been fixed as well before I merge this?

**Comment by JaceThings** [comment]
Yep :)

**Pull request merged**
