### PR TITLE
Use dismiss environment to replace pass into isPresented value

### PR DESCRIPTION
**Pull request by phlpsong**
Use environment `dismiss`  to dismiss the popup sheet.

### CODE REVIEW

**Comment by MrKai77** [comment]
Sorry for the late answer :(
I am currently in the process of remaking the settings window, so I won't be merging this. Thank you very much for the effort though :)

**Comment by phlpsong** [comment]
Sure, it's fine 😉 Looking forward to the new remake settings page~

**Comment by MrKai77** [comment]
Thanks! Here's a sneak peek: https://fxtwitter.com/JaceThings/status/1779273820626415766

**Comment by phlpsong** [comment]
Look amazing！

**Pull request closed without merging**
